export default [
    {
      id: 1,
      photo: 'image2.svg',
      priceC: '5555',
      price: '1111',
      name: "Raspberry Pi 3",
      discount: '-15%',
      count: '1',
    },
    {
      id: 2,
      photo: 'image2.svg',
      priceC: '',
      price: '2222',
      name: "Raspberry Pi 3",
      discount: '-15%',
      count: '1',
    },
    {
      id: 3,
      photo: 'image2.svg',
      priceC: '99999',
      price: '3333',
      name: "три",
      discount: '-15%',
      count: '1',
    },
    {
        id: 4,
        photo: 'image2.svg',
        priceC: '',
        price: '4444',
        name: "четыре",
        discount: '-15%',
        count: '1',
    },
    {
        id: 5,
        photo: 'image2.svg',
        priceC: '',
        price: '5555',
        name: "пять",
        discount: '-15%',
        count: '1',
    },
    {
        id: 6,
        photo: 'image2.svg',
        priceC: '888888',
        price: '7878',
        name: "шестьь",
        discount: '-15%',
        count: '1',
    },
      
  ]
  